CREATE TABLE `sys_order` (
	`ID` VARCHAR(40) NOT NULL COMMENT '主键',
	`VERSION` INT NOT NULL DEFAULT 0 COMMENT '版本',
	`CODE` VARCHAR(20) NULL DEFAULT NULL COMMENT '编码',
	`NAME` VARCHAR(40) NULL DEFAULT NULL COMMENT '名称',
	`CREATIONTIME` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
	`REMARK` VARCHAR(100) NULL DEFAULT NULL COMMENT '备注',
	INDEX `PK` (`ID`)
)
COMMENT='订单表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;